install.packages("git2r")
library(git2r)
library(usethis)
usethis::use_pkgdown()
pkgdown::build_site()

devtools::install_github("jaubele/cdetidy")
library(cdetidy)
devtools::load_all()
devtools::document()
