
A tidyverse-style toolkit for working with California Department of Education (CDE) datasets.

The `cdetidy` R package contains a collection of functions developed by the Orange County Department of Education (OCDE) for efficiently transforming, validating, labeling, and exporting public CDE datasets. It is tailored to support internal OCDE workflows related to data warehousing, reporting, and dashboard preparation — but may be useful for others working with similar data structures.

---

## Key Features


- Clean and validate CDS codes (county, district, school)
- Apply standardized group labeling across multiple CDE domains (race, grade, subgroup, etc.)
- Generate and log SQL schema definitions for warehouse tables
- Automatically create bulk-insertable flat files with logging and metadata
- Detect schema drift across years for rebuild planning

- Clean and validate **CDS codes** (county, district, school)
- Apply standardized **group labeling** across multiple CDE domains (race, grade, subgroup, etc.)
- Generate and log **SQL schema definitions** for warehouse tables
- Automatically create **bulk-insertable flat files** with logging and metadata
- Detect **schema drift** across years for rebuild planning
- QA utilities for checking primary keys, suppression rules, and table structure
- Functions included can assist in ETL process of CDE data

---

## Installation

```r
install.packages("devtools")  # if not already installed
devtools::install_github("jaubele/cdetidy")
library(cdetidy)
